# This is a basic workflow to help you get started with Actions

name: ED7

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  show-env:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hej fr√•n GitHub Actions"
      NAME: "Student"
    steps:
      - name: Print environment variables
        run: |
          echo "Greeting: $GREETING"
          echo "Name: $NAME"
          echo "Github actor: $GITHUB_ACTOR"
          echo "Run number: $GITHUB_RUN_NUMBER"
