name: ZY7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Ser till att pipeline kan starta manuellt
  workflow_dispatch:
    inputs:
      # log_errors styr om fel-loggar ska sparas när tester misslyckas.
      log_errors:
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_failed: ${{ steps.test_step.outcome != 'success' }}

    steps:
      # Checks-out koden i repot under $GITHUB_WORKSPACE så att jobs kan hämta den
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installerar och konfigurerar Python 3.11 i workflow-miljön
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installera python dependencies i GitHub Actions-miljön.
      # Ser till att tester och skript fungerar
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run unit and integration tests
      # Ser till att koden som hämtar API fungerar innan docker-imagen byggs och pushas.
      - name: Run tests
        id: test_step
        run: pytest --maxfail=1 --disable-warnings
        
      - name: Save error log if tests failed AND log_errors=true
        if: ${{ failure() && github.event.inputs.log_errors == 'true' }}
        run: |
          mkdir -p logs
          echo "tests failed at $(date)" > logs/error_log.txt
          
# sparar artefakten
      - name: Upload error log artifact
        if: ${{ steps.test_step.outcome != 'success' && github.event.inputs.log_errors == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: error_log
          path: logs/error_log.txt
        
  # docker-jobbet beroende av test-jobbet via "needs"
  docker:
    runs-on: ubuntu-latest
    needs: test # ser till att docker-jobbet körs efter test-jobbet
    # If-satsen stoppar hela docker-jobbet om testerna misslyckats
    if: ${{ needs.test.outputs.test_failed == 'false' }}
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/jobads-dashboard-zy
    steps:
      - uses: actions/checkout@v4
      
      # Logga in på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build och push docker-image till docker hub
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .          # Dockerfile finns i roten
          file: Dockerfile    # Dockerfile-namn
          push: true          # pushar automatiskt till Docker Hub
          tags: zamzamy/jobads-dashboard-zy:latest # namnet på imagen + tag
