# This is a basic workflow to help you get started with Actions

name: ZY7

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out koden i repot under $GITHUB_WORKSPACE så att jobs kan hämta den
      - name: Checkout reposatory
        uses: actions/checkout@v4

      # Installerar och konfigurerar Python 3.11 i workflow-miljön.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # Installera python dependencies i GitHub Actions-miljön.
      # Utan detta skulle workflow:et sakna nödvändiga paket och testerna misslyckas.
      # Ser till att tester och skript fungerar i en ren CI/CD-miljö
      - name: Install dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      # Run unit and intergration tests
      # Ser till att koden fungerar som förväntat innan docker-imagen byggs och pushas.
      - name: run tests
        run: pytest --maxfail=1 --disable-warnings

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Login to Docker Hub
      - name: Build docker image
        run: docker build -t dashboard:latest  .

      # Push docker image to docker hub
      - name: Push docker image
        run: docker push dashboard:latest

      
