name: ZY7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/jobads-dashboard-zy

    steps:
      # Checks-out koden i repot under $GITHUB_WORKSPACE så att jobs kan hämta den
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installerar och konfigurerar Python 3.11 i workflow-miljön
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installera python dependencies i GitHub Actions-miljön.
      # Ser till att tester och skript fungerar
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run unit and integration tests
      # Ser till att koden som hämtar API fungerar innan docker-imagen byggs och pushas.
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings

      # Logga in på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build och push docker-image till docker hub
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .          # Dockerfile finns i roten
          file: Dockerfile    # Dockerfile-namn
          push: true          # pushar automatiskt till Docker Hub
          tags: zamzamy/jobads-dashboard-zy:latest # namnet på imagen + tag
